# Generated by Django 5.1.5 on 2025-04-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.CharField(
                choices=[
                    ("not completed", "Not Completed"),
                    ("completed", "Completed"),
                ],
                default="not completed",
                max_length=20,
            ),
        ),
    ]
