# Generated by Django 5.1.5 on 2025-05-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_created_by_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(choices=[(1, "Low"), (2, "Medium"), (3, "High")]),
        ),
    ]
